# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Radka\Desktop\BP\EACirc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Radka\Desktop\BP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	"C:\Program Files (x86)\CMake\bin\ctest.exe" --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /d C:\Users\Radka\Desktop\BP && $(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Radka\Desktop\BP\CMakeFiles C:\Users\Radka\Desktop\BP\EACirc\CMakeFiles\progress.marks
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f CMakeFiles\Makefile2 EACirc/all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Radka\Desktop\BP\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f CMakeFiles\Makefile2 EACirc/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f CMakeFiles\Makefile2 EACirc/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f CMakeFiles\Makefile2 EACirc/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /d C:\Users\Radka\Desktop\BP && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
EACirc/CMakeFiles/eacirc.dir/rule:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f CMakeFiles\Makefile2 EACirc/CMakeFiles/eacirc.dir/rule
.PHONY : EACirc/CMakeFiles/eacirc.dir/rule

# Convenience name for target.
eacirc: EACirc/CMakeFiles/eacirc.dir/rule

.PHONY : eacirc

# fast build rule for target.
eacirc/fast:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/build
.PHONY : eacirc/fast

CommonFnc.obj: CommonFnc.cpp.obj

.PHONY : CommonFnc.obj

# target to build an object file
CommonFnc.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/CommonFnc.cpp.obj
.PHONY : CommonFnc.cpp.obj

CommonFnc.i: CommonFnc.cpp.i

.PHONY : CommonFnc.i

# target to preprocess a source file
CommonFnc.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/CommonFnc.cpp.i
.PHONY : CommonFnc.cpp.i

CommonFnc.s: CommonFnc.cpp.s

.PHONY : CommonFnc.s

# target to generate assembly for a file
CommonFnc.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/CommonFnc.cpp.s
.PHONY : CommonFnc.cpp.s

EACglobals.obj: EACglobals.cpp.obj

.PHONY : EACglobals.obj

# target to build an object file
EACglobals.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/EACglobals.cpp.obj
.PHONY : EACglobals.cpp.obj

EACglobals.i: EACglobals.cpp.i

.PHONY : EACglobals.i

# target to preprocess a source file
EACglobals.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/EACglobals.cpp.i
.PHONY : EACglobals.cpp.i

EACglobals.s: EACglobals.cpp.s

.PHONY : EACglobals.s

# target to generate assembly for a file
EACglobals.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/EACglobals.cpp.s
.PHONY : EACglobals.cpp.s

EACirc.obj: EACirc.cpp.obj

.PHONY : EACirc.obj

# target to build an object file
EACirc.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/EACirc.cpp.obj
.PHONY : EACirc.cpp.obj

EACirc.i: EACirc.cpp.i

.PHONY : EACirc.i

# target to preprocess a source file
EACirc.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/EACirc.cpp.i
.PHONY : EACirc.cpp.i

EACirc.s: EACirc.cpp.s

.PHONY : EACirc.s

# target to generate assembly for a file
EACirc.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/EACirc.cpp.s
.PHONY : EACirc.cpp.s

Finishers.obj: Finishers.cpp.obj

.PHONY : Finishers.obj

# target to build an object file
Finishers.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/Finishers.cpp.obj
.PHONY : Finishers.cpp.obj

Finishers.i: Finishers.cpp.i

.PHONY : Finishers.i

# target to preprocess a source file
Finishers.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/Finishers.cpp.i
.PHONY : Finishers.cpp.i

Finishers.s: Finishers.cpp.s

.PHONY : Finishers.s

# target to generate assembly for a file
Finishers.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/Finishers.cpp.s
.PHONY : Finishers.cpp.s

Logger.obj: Logger.cpp.obj

.PHONY : Logger.obj

# target to build an object file
Logger.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/Logger.cpp.obj
.PHONY : Logger.cpp.obj

Logger.i: Logger.cpp.i

.PHONY : Logger.i

# target to preprocess a source file
Logger.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/Logger.cpp.i
.PHONY : Logger.cpp.i

Logger.s: Logger.cpp.s

.PHONY : Logger.s

# target to generate assembly for a file
Logger.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/Logger.cpp.s
.PHONY : Logger.cpp.s

Main.obj: Main.cpp.obj

.PHONY : Main.obj

# target to build an object file
Main.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/Main.cpp.obj
.PHONY : Main.cpp.obj

Main.i: Main.cpp.i

.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s

.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/Main.cpp.s
.PHONY : Main.cpp.s

Status.obj: Status.cpp.obj

.PHONY : Status.obj

# target to build an object file
Status.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/Status.cpp.obj
.PHONY : Status.cpp.obj

Status.i: Status.cpp.i

.PHONY : Status.i

# target to preprocess a source file
Status.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/Status.cpp.i
.PHONY : Status.cpp.i

Status.s: Status.cpp.s

.PHONY : Status.s

# target to generate assembly for a file
Status.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/Status.cpp.s
.PHONY : Status.cpp.s

XMLProcessor.obj: XMLProcessor.cpp.obj

.PHONY : XMLProcessor.obj

# target to build an object file
XMLProcessor.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/XMLProcessor.cpp.obj
.PHONY : XMLProcessor.cpp.obj

XMLProcessor.i: XMLProcessor.cpp.i

.PHONY : XMLProcessor.i

# target to preprocess a source file
XMLProcessor.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/XMLProcessor.cpp.i
.PHONY : XMLProcessor.cpp.i

XMLProcessor.s: XMLProcessor.cpp.s

.PHONY : XMLProcessor.s

# target to generate assembly for a file
XMLProcessor.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/XMLProcessor.cpp.s
.PHONY : XMLProcessor.cpp.s

circuit/ICircuit.obj: circuit/ICircuit.cpp.obj

.PHONY : circuit/ICircuit.obj

# target to build an object file
circuit/ICircuit.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/ICircuit.cpp.obj
.PHONY : circuit/ICircuit.cpp.obj

circuit/ICircuit.i: circuit/ICircuit.cpp.i

.PHONY : circuit/ICircuit.i

# target to preprocess a source file
circuit/ICircuit.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/ICircuit.cpp.i
.PHONY : circuit/ICircuit.cpp.i

circuit/ICircuit.s: circuit/ICircuit.cpp.s

.PHONY : circuit/ICircuit.s

# target to generate assembly for a file
circuit/ICircuit.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/ICircuit.cpp.s
.PHONY : circuit/ICircuit.cpp.s

circuit/ICircuitIO.obj: circuit/ICircuitIO.cpp.obj

.PHONY : circuit/ICircuitIO.obj

# target to build an object file
circuit/ICircuitIO.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/ICircuitIO.cpp.obj
.PHONY : circuit/ICircuitIO.cpp.obj

circuit/ICircuitIO.i: circuit/ICircuitIO.cpp.i

.PHONY : circuit/ICircuitIO.i

# target to preprocess a source file
circuit/ICircuitIO.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/ICircuitIO.cpp.i
.PHONY : circuit/ICircuitIO.cpp.i

circuit/ICircuitIO.s: circuit/ICircuitIO.cpp.s

.PHONY : circuit/ICircuitIO.s

# target to generate assembly for a file
circuit/ICircuitIO.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/ICircuitIO.cpp.s
.PHONY : circuit/ICircuitIO.cpp.s

circuit/gate/GAGateCallbacks.obj: circuit/gate/GAGateCallbacks.cpp.obj

.PHONY : circuit/gate/GAGateCallbacks.obj

# target to build an object file
circuit/gate/GAGateCallbacks.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GAGateCallbacks.cpp.obj
.PHONY : circuit/gate/GAGateCallbacks.cpp.obj

circuit/gate/GAGateCallbacks.i: circuit/gate/GAGateCallbacks.cpp.i

.PHONY : circuit/gate/GAGateCallbacks.i

# target to preprocess a source file
circuit/gate/GAGateCallbacks.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GAGateCallbacks.cpp.i
.PHONY : circuit/gate/GAGateCallbacks.cpp.i

circuit/gate/GAGateCallbacks.s: circuit/gate/GAGateCallbacks.cpp.s

.PHONY : circuit/gate/GAGateCallbacks.s

# target to generate assembly for a file
circuit/gate/GAGateCallbacks.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GAGateCallbacks.cpp.s
.PHONY : circuit/gate/GAGateCallbacks.cpp.s

circuit/gate/GateCircuit.obj: circuit/gate/GateCircuit.cpp.obj

.PHONY : circuit/gate/GateCircuit.obj

# target to build an object file
circuit/gate/GateCircuit.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GateCircuit.cpp.obj
.PHONY : circuit/gate/GateCircuit.cpp.obj

circuit/gate/GateCircuit.i: circuit/gate/GateCircuit.cpp.i

.PHONY : circuit/gate/GateCircuit.i

# target to preprocess a source file
circuit/gate/GateCircuit.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GateCircuit.cpp.i
.PHONY : circuit/gate/GateCircuit.cpp.i

circuit/gate/GateCircuit.s: circuit/gate/GateCircuit.cpp.s

.PHONY : circuit/gate/GateCircuit.s

# target to generate assembly for a file
circuit/gate/GateCircuit.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GateCircuit.cpp.s
.PHONY : circuit/gate/GateCircuit.cpp.s

circuit/gate/GateCircuitIO.obj: circuit/gate/GateCircuitIO.cpp.obj

.PHONY : circuit/gate/GateCircuitIO.obj

# target to build an object file
circuit/gate/GateCircuitIO.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GateCircuitIO.cpp.obj
.PHONY : circuit/gate/GateCircuitIO.cpp.obj

circuit/gate/GateCircuitIO.i: circuit/gate/GateCircuitIO.cpp.i

.PHONY : circuit/gate/GateCircuitIO.i

# target to preprocess a source file
circuit/gate/GateCircuitIO.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GateCircuitIO.cpp.i
.PHONY : circuit/gate/GateCircuitIO.cpp.i

circuit/gate/GateCircuitIO.s: circuit/gate/GateCircuitIO.cpp.s

.PHONY : circuit/gate/GateCircuitIO.s

# target to generate assembly for a file
circuit/gate/GateCircuitIO.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GateCircuitIO.cpp.s
.PHONY : circuit/gate/GateCircuitIO.cpp.s

circuit/gate/GateCommonFunctions.obj: circuit/gate/GateCommonFunctions.cpp.obj

.PHONY : circuit/gate/GateCommonFunctions.obj

# target to build an object file
circuit/gate/GateCommonFunctions.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GateCommonFunctions.cpp.obj
.PHONY : circuit/gate/GateCommonFunctions.cpp.obj

circuit/gate/GateCommonFunctions.i: circuit/gate/GateCommonFunctions.cpp.i

.PHONY : circuit/gate/GateCommonFunctions.i

# target to preprocess a source file
circuit/gate/GateCommonFunctions.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GateCommonFunctions.cpp.i
.PHONY : circuit/gate/GateCommonFunctions.cpp.i

circuit/gate/GateCommonFunctions.s: circuit/gate/GateCommonFunctions.cpp.s

.PHONY : circuit/gate/GateCommonFunctions.s

# target to generate assembly for a file
circuit/gate/GateCommonFunctions.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GateCommonFunctions.cpp.s
.PHONY : circuit/gate/GateCommonFunctions.cpp.s

circuit/gate/GateInterpreter.obj: circuit/gate/GateInterpreter.cpp.obj

.PHONY : circuit/gate/GateInterpreter.obj

# target to build an object file
circuit/gate/GateInterpreter.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GateInterpreter.cpp.obj
.PHONY : circuit/gate/GateInterpreter.cpp.obj

circuit/gate/GateInterpreter.i: circuit/gate/GateInterpreter.cpp.i

.PHONY : circuit/gate/GateInterpreter.i

# target to preprocess a source file
circuit/gate/GateInterpreter.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GateInterpreter.cpp.i
.PHONY : circuit/gate/GateInterpreter.cpp.i

circuit/gate/GateInterpreter.s: circuit/gate/GateInterpreter.cpp.s

.PHONY : circuit/gate/GateInterpreter.s

# target to generate assembly for a file
circuit/gate/GateInterpreter.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/GateInterpreter.cpp.s
.PHONY : circuit/gate/GateInterpreter.cpp.s

circuit/gate/JVMSimulator.obj: circuit/gate/JVMSimulator.cpp.obj

.PHONY : circuit/gate/JVMSimulator.obj

# target to build an object file
circuit/gate/JVMSimulator.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/JVMSimulator.cpp.obj
.PHONY : circuit/gate/JVMSimulator.cpp.obj

circuit/gate/JVMSimulator.i: circuit/gate/JVMSimulator.cpp.i

.PHONY : circuit/gate/JVMSimulator.i

# target to preprocess a source file
circuit/gate/JVMSimulator.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/JVMSimulator.cpp.i
.PHONY : circuit/gate/JVMSimulator.cpp.i

circuit/gate/JVMSimulator.s: circuit/gate/JVMSimulator.cpp.s

.PHONY : circuit/gate/JVMSimulator.s

# target to generate assembly for a file
circuit/gate/JVMSimulator.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate/JVMSimulator.cpp.s
.PHONY : circuit/gate/JVMSimulator.cpp.s

circuit/gate2/Converter.obj: circuit/gate2/Converter.cpp.obj

.PHONY : circuit/gate2/Converter.obj

# target to build an object file
circuit/gate2/Converter.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate2/Converter.cpp.obj
.PHONY : circuit/gate2/Converter.cpp.obj

circuit/gate2/Converter.i: circuit/gate2/Converter.cpp.i

.PHONY : circuit/gate2/Converter.i

# target to preprocess a source file
circuit/gate2/Converter.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate2/Converter.cpp.i
.PHONY : circuit/gate2/Converter.cpp.i

circuit/gate2/Converter.s: circuit/gate2/Converter.cpp.s

.PHONY : circuit/gate2/Converter.s

# target to generate assembly for a file
circuit/gate2/Converter.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate2/Converter.cpp.s
.PHONY : circuit/gate2/Converter.cpp.s

circuit/gate2/CpuGate.obj: circuit/gate2/CpuGate.cpp.obj

.PHONY : circuit/gate2/CpuGate.obj

# target to build an object file
circuit/gate2/CpuGate.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate2/CpuGate.cpp.obj
.PHONY : circuit/gate2/CpuGate.cpp.obj

circuit/gate2/CpuGate.i: circuit/gate2/CpuGate.cpp.i

.PHONY : circuit/gate2/CpuGate.i

# target to preprocess a source file
circuit/gate2/CpuGate.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate2/CpuGate.cpp.i
.PHONY : circuit/gate2/CpuGate.cpp.i

circuit/gate2/CpuGate.s: circuit/gate2/CpuGate.cpp.s

.PHONY : circuit/gate2/CpuGate.s

# target to generate assembly for a file
circuit/gate2/CpuGate.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate2/CpuGate.cpp.s
.PHONY : circuit/gate2/CpuGate.cpp.s

circuit/gate2/GaGate.obj: circuit/gate2/GaGate.cpp.obj

.PHONY : circuit/gate2/GaGate.obj

# target to build an object file
circuit/gate2/GaGate.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate2/GaGate.cpp.obj
.PHONY : circuit/gate2/GaGate.cpp.obj

circuit/gate2/GaGate.i: circuit/gate2/GaGate.cpp.i

.PHONY : circuit/gate2/GaGate.i

# target to preprocess a source file
circuit/gate2/GaGate.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate2/GaGate.cpp.i
.PHONY : circuit/gate2/GaGate.cpp.i

circuit/gate2/GaGate.s: circuit/gate2/GaGate.cpp.s

.PHONY : circuit/gate2/GaGate.s

# target to generate assembly for a file
circuit/gate2/GaGate.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate2/GaGate.cpp.s
.PHONY : circuit/gate2/GaGate.cpp.s

circuit/gate2/Gate2.obj: circuit/gate2/Gate2.cpp.obj

.PHONY : circuit/gate2/Gate2.obj

# target to build an object file
circuit/gate2/Gate2.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate2/Gate2.cpp.obj
.PHONY : circuit/gate2/Gate2.cpp.obj

circuit/gate2/Gate2.i: circuit/gate2/Gate2.cpp.i

.PHONY : circuit/gate2/Gate2.i

# target to preprocess a source file
circuit/gate2/Gate2.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate2/Gate2.cpp.i
.PHONY : circuit/gate2/Gate2.cpp.i

circuit/gate2/Gate2.s: circuit/gate2/Gate2.cpp.s

.PHONY : circuit/gate2/Gate2.s

# target to generate assembly for a file
circuit/gate2/Gate2.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/gate2/Gate2.cpp.s
.PHONY : circuit/gate2/Gate2.cpp.s

circuit/polynomial/GAPolyCallbacks.obj: circuit/polynomial/GAPolyCallbacks.cpp.obj

.PHONY : circuit/polynomial/GAPolyCallbacks.obj

# target to build an object file
circuit/polynomial/GAPolyCallbacks.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/GAPolyCallbacks.cpp.obj
.PHONY : circuit/polynomial/GAPolyCallbacks.cpp.obj

circuit/polynomial/GAPolyCallbacks.i: circuit/polynomial/GAPolyCallbacks.cpp.i

.PHONY : circuit/polynomial/GAPolyCallbacks.i

# target to preprocess a source file
circuit/polynomial/GAPolyCallbacks.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/GAPolyCallbacks.cpp.i
.PHONY : circuit/polynomial/GAPolyCallbacks.cpp.i

circuit/polynomial/GAPolyCallbacks.s: circuit/polynomial/GAPolyCallbacks.cpp.s

.PHONY : circuit/polynomial/GAPolyCallbacks.s

# target to generate assembly for a file
circuit/polynomial/GAPolyCallbacks.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/GAPolyCallbacks.cpp.s
.PHONY : circuit/polynomial/GAPolyCallbacks.cpp.s

circuit/polynomial/PolyCommonFunctions.obj: circuit/polynomial/PolyCommonFunctions.cpp.obj

.PHONY : circuit/polynomial/PolyCommonFunctions.obj

# target to build an object file
circuit/polynomial/PolyCommonFunctions.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/PolyCommonFunctions.cpp.obj
.PHONY : circuit/polynomial/PolyCommonFunctions.cpp.obj

circuit/polynomial/PolyCommonFunctions.i: circuit/polynomial/PolyCommonFunctions.cpp.i

.PHONY : circuit/polynomial/PolyCommonFunctions.i

# target to preprocess a source file
circuit/polynomial/PolyCommonFunctions.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/PolyCommonFunctions.cpp.i
.PHONY : circuit/polynomial/PolyCommonFunctions.cpp.i

circuit/polynomial/PolyCommonFunctions.s: circuit/polynomial/PolyCommonFunctions.cpp.s

.PHONY : circuit/polynomial/PolyCommonFunctions.s

# target to generate assembly for a file
circuit/polynomial/PolyCommonFunctions.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/PolyCommonFunctions.cpp.s
.PHONY : circuit/polynomial/PolyCommonFunctions.cpp.s

circuit/polynomial/PolynomialCircuit.obj: circuit/polynomial/PolynomialCircuit.cpp.obj

.PHONY : circuit/polynomial/PolynomialCircuit.obj

# target to build an object file
circuit/polynomial/PolynomialCircuit.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/PolynomialCircuit.cpp.obj
.PHONY : circuit/polynomial/PolynomialCircuit.cpp.obj

circuit/polynomial/PolynomialCircuit.i: circuit/polynomial/PolynomialCircuit.cpp.i

.PHONY : circuit/polynomial/PolynomialCircuit.i

# target to preprocess a source file
circuit/polynomial/PolynomialCircuit.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/PolynomialCircuit.cpp.i
.PHONY : circuit/polynomial/PolynomialCircuit.cpp.i

circuit/polynomial/PolynomialCircuit.s: circuit/polynomial/PolynomialCircuit.cpp.s

.PHONY : circuit/polynomial/PolynomialCircuit.s

# target to generate assembly for a file
circuit/polynomial/PolynomialCircuit.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/PolynomialCircuit.cpp.s
.PHONY : circuit/polynomial/PolynomialCircuit.cpp.s

circuit/polynomial/PolynomialCircuitIO.obj: circuit/polynomial/PolynomialCircuitIO.cpp.obj

.PHONY : circuit/polynomial/PolynomialCircuitIO.obj

# target to build an object file
circuit/polynomial/PolynomialCircuitIO.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/PolynomialCircuitIO.cpp.obj
.PHONY : circuit/polynomial/PolynomialCircuitIO.cpp.obj

circuit/polynomial/PolynomialCircuitIO.i: circuit/polynomial/PolynomialCircuitIO.cpp.i

.PHONY : circuit/polynomial/PolynomialCircuitIO.i

# target to preprocess a source file
circuit/polynomial/PolynomialCircuitIO.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/PolynomialCircuitIO.cpp.i
.PHONY : circuit/polynomial/PolynomialCircuitIO.cpp.i

circuit/polynomial/PolynomialCircuitIO.s: circuit/polynomial/PolynomialCircuitIO.cpp.s

.PHONY : circuit/polynomial/PolynomialCircuitIO.s

# target to generate assembly for a file
circuit/polynomial/PolynomialCircuitIO.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/PolynomialCircuitIO.cpp.s
.PHONY : circuit/polynomial/PolynomialCircuitIO.cpp.s

circuit/polynomial/PolynomialInterpreter.obj: circuit/polynomial/PolynomialInterpreter.cpp.obj

.PHONY : circuit/polynomial/PolynomialInterpreter.obj

# target to build an object file
circuit/polynomial/PolynomialInterpreter.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/PolynomialInterpreter.cpp.obj
.PHONY : circuit/polynomial/PolynomialInterpreter.cpp.obj

circuit/polynomial/PolynomialInterpreter.i: circuit/polynomial/PolynomialInterpreter.cpp.i

.PHONY : circuit/polynomial/PolynomialInterpreter.i

# target to preprocess a source file
circuit/polynomial/PolynomialInterpreter.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/PolynomialInterpreter.cpp.i
.PHONY : circuit/polynomial/PolynomialInterpreter.cpp.i

circuit/polynomial/PolynomialInterpreter.s: circuit/polynomial/PolynomialInterpreter.cpp.s

.PHONY : circuit/polynomial/PolynomialInterpreter.s

# target to generate assembly for a file
circuit/polynomial/PolynomialInterpreter.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/PolynomialInterpreter.cpp.s
.PHONY : circuit/polynomial/PolynomialInterpreter.cpp.s

circuit/polynomial/Term.obj: circuit/polynomial/Term.cpp.obj

.PHONY : circuit/polynomial/Term.obj

# target to build an object file
circuit/polynomial/Term.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/Term.cpp.obj
.PHONY : circuit/polynomial/Term.cpp.obj

circuit/polynomial/Term.i: circuit/polynomial/Term.cpp.i

.PHONY : circuit/polynomial/Term.i

# target to preprocess a source file
circuit/polynomial/Term.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/Term.cpp.i
.PHONY : circuit/polynomial/Term.cpp.i

circuit/polynomial/Term.s: circuit/polynomial/Term.cpp.s

.PHONY : circuit/polynomial/Term.s

# target to generate assembly for a file
circuit/polynomial/Term.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/circuit/polynomial/Term.cpp.s
.PHONY : circuit/polynomial/Term.cpp.s

evaluators/CategoriesEvaluator.obj: evaluators/CategoriesEvaluator.cpp.obj

.PHONY : evaluators/CategoriesEvaluator.obj

# target to build an object file
evaluators/CategoriesEvaluator.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/CategoriesEvaluator.cpp.obj
.PHONY : evaluators/CategoriesEvaluator.cpp.obj

evaluators/CategoriesEvaluator.i: evaluators/CategoriesEvaluator.cpp.i

.PHONY : evaluators/CategoriesEvaluator.i

# target to preprocess a source file
evaluators/CategoriesEvaluator.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/CategoriesEvaluator.cpp.i
.PHONY : evaluators/CategoriesEvaluator.cpp.i

evaluators/CategoriesEvaluator.s: evaluators/CategoriesEvaluator.cpp.s

.PHONY : evaluators/CategoriesEvaluator.s

# target to generate assembly for a file
evaluators/CategoriesEvaluator.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/CategoriesEvaluator.cpp.s
.PHONY : evaluators/CategoriesEvaluator.cpp.s

evaluators/FeatureEvaluator.obj: evaluators/FeatureEvaluator.cpp.obj

.PHONY : evaluators/FeatureEvaluator.obj

# target to build an object file
evaluators/FeatureEvaluator.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/FeatureEvaluator.cpp.obj
.PHONY : evaluators/FeatureEvaluator.cpp.obj

evaluators/FeatureEvaluator.i: evaluators/FeatureEvaluator.cpp.i

.PHONY : evaluators/FeatureEvaluator.i

# target to preprocess a source file
evaluators/FeatureEvaluator.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/FeatureEvaluator.cpp.i
.PHONY : evaluators/FeatureEvaluator.cpp.i

evaluators/FeatureEvaluator.s: evaluators/FeatureEvaluator.cpp.s

.PHONY : evaluators/FeatureEvaluator.s

# target to generate assembly for a file
evaluators/FeatureEvaluator.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/FeatureEvaluator.cpp.s
.PHONY : evaluators/FeatureEvaluator.cpp.s

evaluators/HammingWeightEvaluator.obj: evaluators/HammingWeightEvaluator.cpp.obj

.PHONY : evaluators/HammingWeightEvaluator.obj

# target to build an object file
evaluators/HammingWeightEvaluator.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/HammingWeightEvaluator.cpp.obj
.PHONY : evaluators/HammingWeightEvaluator.cpp.obj

evaluators/HammingWeightEvaluator.i: evaluators/HammingWeightEvaluator.cpp.i

.PHONY : evaluators/HammingWeightEvaluator.i

# target to preprocess a source file
evaluators/HammingWeightEvaluator.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/HammingWeightEvaluator.cpp.i
.PHONY : evaluators/HammingWeightEvaluator.cpp.i

evaluators/HammingWeightEvaluator.s: evaluators/HammingWeightEvaluator.cpp.s

.PHONY : evaluators/HammingWeightEvaluator.s

# target to generate assembly for a file
evaluators/HammingWeightEvaluator.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/HammingWeightEvaluator.cpp.s
.PHONY : evaluators/HammingWeightEvaluator.cpp.s

evaluators/IEvaluator.obj: evaluators/IEvaluator.cpp.obj

.PHONY : evaluators/IEvaluator.obj

# target to build an object file
evaluators/IEvaluator.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/IEvaluator.cpp.obj
.PHONY : evaluators/IEvaluator.cpp.obj

evaluators/IEvaluator.i: evaluators/IEvaluator.cpp.i

.PHONY : evaluators/IEvaluator.i

# target to preprocess a source file
evaluators/IEvaluator.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/IEvaluator.cpp.i
.PHONY : evaluators/IEvaluator.cpp.i

evaluators/IEvaluator.s: evaluators/IEvaluator.cpp.s

.PHONY : evaluators/IEvaluator.s

# target to generate assembly for a file
evaluators/IEvaluator.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/IEvaluator.cpp.s
.PHONY : evaluators/IEvaluator.cpp.s

evaluators/TopBitEvaluator.obj: evaluators/TopBitEvaluator.cpp.obj

.PHONY : evaluators/TopBitEvaluator.obj

# target to build an object file
evaluators/TopBitEvaluator.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/TopBitEvaluator.cpp.obj
.PHONY : evaluators/TopBitEvaluator.cpp.obj

evaluators/TopBitEvaluator.i: evaluators/TopBitEvaluator.cpp.i

.PHONY : evaluators/TopBitEvaluator.i

# target to preprocess a source file
evaluators/TopBitEvaluator.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/TopBitEvaluator.cpp.i
.PHONY : evaluators/TopBitEvaluator.cpp.i

evaluators/TopBitEvaluator.s: evaluators/TopBitEvaluator.cpp.s

.PHONY : evaluators/TopBitEvaluator.s

# target to generate assembly for a file
evaluators/TopBitEvaluator.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/evaluators/TopBitEvaluator.cpp.s
.PHONY : evaluators/TopBitEvaluator.cpp.s

generators/BiasRndGen.obj: generators/BiasRndGen.cpp.obj

.PHONY : generators/BiasRndGen.obj

# target to build an object file
generators/BiasRndGen.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/BiasRndGen.cpp.obj
.PHONY : generators/BiasRndGen.cpp.obj

generators/BiasRndGen.i: generators/BiasRndGen.cpp.i

.PHONY : generators/BiasRndGen.i

# target to preprocess a source file
generators/BiasRndGen.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/BiasRndGen.cpp.i
.PHONY : generators/BiasRndGen.cpp.i

generators/BiasRndGen.s: generators/BiasRndGen.cpp.s

.PHONY : generators/BiasRndGen.s

# target to generate assembly for a file
generators/BiasRndGen.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/BiasRndGen.cpp.s
.PHONY : generators/BiasRndGen.cpp.s

generators/IRndGen.obj: generators/IRndGen.cpp.obj

.PHONY : generators/IRndGen.obj

# target to build an object file
generators/IRndGen.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/IRndGen.cpp.obj
.PHONY : generators/IRndGen.cpp.obj

generators/IRndGen.i: generators/IRndGen.cpp.i

.PHONY : generators/IRndGen.i

# target to preprocess a source file
generators/IRndGen.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/IRndGen.cpp.i
.PHONY : generators/IRndGen.cpp.i

generators/IRndGen.s: generators/IRndGen.cpp.s

.PHONY : generators/IRndGen.s

# target to generate assembly for a file
generators/IRndGen.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/IRndGen.cpp.s
.PHONY : generators/IRndGen.cpp.s

generators/MD5RndGen.obj: generators/MD5RndGen.cpp.obj

.PHONY : generators/MD5RndGen.obj

# target to build an object file
generators/MD5RndGen.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/MD5RndGen.cpp.obj
.PHONY : generators/MD5RndGen.cpp.obj

generators/MD5RndGen.i: generators/MD5RndGen.cpp.i

.PHONY : generators/MD5RndGen.i

# target to preprocess a source file
generators/MD5RndGen.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/MD5RndGen.cpp.i
.PHONY : generators/MD5RndGen.cpp.i

generators/MD5RndGen.s: generators/MD5RndGen.cpp.s

.PHONY : generators/MD5RndGen.s

# target to generate assembly for a file
generators/MD5RndGen.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/MD5RndGen.cpp.s
.PHONY : generators/MD5RndGen.cpp.s

generators/QuantumRndGen.obj: generators/QuantumRndGen.cpp.obj

.PHONY : generators/QuantumRndGen.obj

# target to build an object file
generators/QuantumRndGen.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/QuantumRndGen.cpp.obj
.PHONY : generators/QuantumRndGen.cpp.obj

generators/QuantumRndGen.i: generators/QuantumRndGen.cpp.i

.PHONY : generators/QuantumRndGen.i

# target to preprocess a source file
generators/QuantumRndGen.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/QuantumRndGen.cpp.i
.PHONY : generators/QuantumRndGen.cpp.i

generators/QuantumRndGen.s: generators/QuantumRndGen.cpp.s

.PHONY : generators/QuantumRndGen.s

# target to generate assembly for a file
generators/QuantumRndGen.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/QuantumRndGen.cpp.s
.PHONY : generators/QuantumRndGen.cpp.s

generators/md5.obj: generators/md5.cpp.obj

.PHONY : generators/md5.obj

# target to build an object file
generators/md5.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/md5.cpp.obj
.PHONY : generators/md5.cpp.obj

generators/md5.i: generators/md5.cpp.i

.PHONY : generators/md5.i

# target to preprocess a source file
generators/md5.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/md5.cpp.i
.PHONY : generators/md5.cpp.i

generators/md5.s: generators/md5.cpp.s

.PHONY : generators/md5.s

# target to generate assembly for a file
generators/md5.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/generators/md5.cpp.s
.PHONY : generators/md5.cpp.s

projects/IProject.obj: projects/IProject.cpp.obj

.PHONY : projects/IProject.obj

# target to build an object file
projects/IProject.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/projects/IProject.cpp.obj
.PHONY : projects/IProject.cpp.obj

projects/IProject.i: projects/IProject.cpp.i

.PHONY : projects/IProject.i

# target to preprocess a source file
projects/IProject.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/projects/IProject.cpp.i
.PHONY : projects/IProject.cpp.i

projects/IProject.s: projects/IProject.cpp.s

.PHONY : projects/IProject.s

# target to generate assembly for a file
projects/IProject.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/projects/IProject.cpp.s
.PHONY : projects/IProject.cpp.s

projects/files/filesProject.obj: projects/files/filesProject.cpp.obj

.PHONY : projects/files/filesProject.obj

# target to build an object file
projects/files/filesProject.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/projects/files/filesProject.cpp.obj
.PHONY : projects/files/filesProject.cpp.obj

projects/files/filesProject.i: projects/files/filesProject.cpp.i

.PHONY : projects/files/filesProject.i

# target to preprocess a source file
projects/files/filesProject.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/projects/files/filesProject.cpp.i
.PHONY : projects/files/filesProject.cpp.i

projects/files/filesProject.s: projects/files/filesProject.cpp.s

.PHONY : projects/files/filesProject.s

# target to generate assembly for a file
projects/files/filesProject.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/projects/files/filesProject.cpp.s
.PHONY : projects/files/filesProject.cpp.s

projects/pregenerated_tv/PregeneratedTvProject.obj: projects/pregenerated_tv/PregeneratedTvProject.cpp.obj

.PHONY : projects/pregenerated_tv/PregeneratedTvProject.obj

# target to build an object file
projects/pregenerated_tv/PregeneratedTvProject.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/projects/pregenerated_tv/PregeneratedTvProject.cpp.obj
.PHONY : projects/pregenerated_tv/PregeneratedTvProject.cpp.obj

projects/pregenerated_tv/PregeneratedTvProject.i: projects/pregenerated_tv/PregeneratedTvProject.cpp.i

.PHONY : projects/pregenerated_tv/PregeneratedTvProject.i

# target to preprocess a source file
projects/pregenerated_tv/PregeneratedTvProject.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/projects/pregenerated_tv/PregeneratedTvProject.cpp.i
.PHONY : projects/pregenerated_tv/PregeneratedTvProject.cpp.i

projects/pregenerated_tv/PregeneratedTvProject.s: projects/pregenerated_tv/PregeneratedTvProject.cpp.s

.PHONY : projects/pregenerated_tv/PregeneratedTvProject.s

# target to generate assembly for a file
projects/pregenerated_tv/PregeneratedTvProject.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/projects/pregenerated_tv/PregeneratedTvProject.cpp.s
.PHONY : projects/pregenerated_tv/PregeneratedTvProject.cpp.s

self_tests/TestConfigurator.obj: self_tests/TestConfigurator.cpp.obj

.PHONY : self_tests/TestConfigurator.obj

# target to build an object file
self_tests/TestConfigurator.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/self_tests/TestConfigurator.cpp.obj
.PHONY : self_tests/TestConfigurator.cpp.obj

self_tests/TestConfigurator.i: self_tests/TestConfigurator.cpp.i

.PHONY : self_tests/TestConfigurator.i

# target to preprocess a source file
self_tests/TestConfigurator.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/self_tests/TestConfigurator.cpp.i
.PHONY : self_tests/TestConfigurator.cpp.i

self_tests/TestConfigurator.s: self_tests/TestConfigurator.cpp.s

.PHONY : self_tests/TestConfigurator.s

# target to generate assembly for a file
self_tests/TestConfigurator.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/self_tests/TestConfigurator.cpp.s
.PHONY : self_tests/TestConfigurator.cpp.s

self_tests/Tests.obj: self_tests/Tests.cpp.obj

.PHONY : self_tests/Tests.obj

# target to build an object file
self_tests/Tests.cpp.obj:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/self_tests/Tests.cpp.obj
.PHONY : self_tests/Tests.cpp.obj

self_tests/Tests.i: self_tests/Tests.cpp.i

.PHONY : self_tests/Tests.i

# target to preprocess a source file
self_tests/Tests.cpp.i:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/self_tests/Tests.cpp.i
.PHONY : self_tests/Tests.cpp.i

self_tests/Tests.s: self_tests/Tests.cpp.s

.PHONY : self_tests/Tests.s

# target to generate assembly for a file
self_tests/Tests.cpp.s:
	cd /d C:\Users\Radka\Desktop\BP && $(MAKE) -f EACirc\CMakeFiles\eacirc.dir\build.make EACirc/CMakeFiles/eacirc.dir/self_tests/Tests.cpp.s
.PHONY : self_tests/Tests.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... eacirc
	@echo ... test
	@echo ... CommonFnc.obj
	@echo ... CommonFnc.i
	@echo ... CommonFnc.s
	@echo ... EACglobals.obj
	@echo ... EACglobals.i
	@echo ... EACglobals.s
	@echo ... EACirc.obj
	@echo ... EACirc.i
	@echo ... EACirc.s
	@echo ... Finishers.obj
	@echo ... Finishers.i
	@echo ... Finishers.s
	@echo ... Logger.obj
	@echo ... Logger.i
	@echo ... Logger.s
	@echo ... Main.obj
	@echo ... Main.i
	@echo ... Main.s
	@echo ... Status.obj
	@echo ... Status.i
	@echo ... Status.s
	@echo ... XMLProcessor.obj
	@echo ... XMLProcessor.i
	@echo ... XMLProcessor.s
	@echo ... circuit/ICircuit.obj
	@echo ... circuit/ICircuit.i
	@echo ... circuit/ICircuit.s
	@echo ... circuit/ICircuitIO.obj
	@echo ... circuit/ICircuitIO.i
	@echo ... circuit/ICircuitIO.s
	@echo ... circuit/gate/GAGateCallbacks.obj
	@echo ... circuit/gate/GAGateCallbacks.i
	@echo ... circuit/gate/GAGateCallbacks.s
	@echo ... circuit/gate/GateCircuit.obj
	@echo ... circuit/gate/GateCircuit.i
	@echo ... circuit/gate/GateCircuit.s
	@echo ... circuit/gate/GateCircuitIO.obj
	@echo ... circuit/gate/GateCircuitIO.i
	@echo ... circuit/gate/GateCircuitIO.s
	@echo ... circuit/gate/GateCommonFunctions.obj
	@echo ... circuit/gate/GateCommonFunctions.i
	@echo ... circuit/gate/GateCommonFunctions.s
	@echo ... circuit/gate/GateInterpreter.obj
	@echo ... circuit/gate/GateInterpreter.i
	@echo ... circuit/gate/GateInterpreter.s
	@echo ... circuit/gate/JVMSimulator.obj
	@echo ... circuit/gate/JVMSimulator.i
	@echo ... circuit/gate/JVMSimulator.s
	@echo ... circuit/gate2/Converter.obj
	@echo ... circuit/gate2/Converter.i
	@echo ... circuit/gate2/Converter.s
	@echo ... circuit/gate2/CpuGate.obj
	@echo ... circuit/gate2/CpuGate.i
	@echo ... circuit/gate2/CpuGate.s
	@echo ... circuit/gate2/GaGate.obj
	@echo ... circuit/gate2/GaGate.i
	@echo ... circuit/gate2/GaGate.s
	@echo ... circuit/gate2/Gate2.obj
	@echo ... circuit/gate2/Gate2.i
	@echo ... circuit/gate2/Gate2.s
	@echo ... circuit/polynomial/GAPolyCallbacks.obj
	@echo ... circuit/polynomial/GAPolyCallbacks.i
	@echo ... circuit/polynomial/GAPolyCallbacks.s
	@echo ... circuit/polynomial/PolyCommonFunctions.obj
	@echo ... circuit/polynomial/PolyCommonFunctions.i
	@echo ... circuit/polynomial/PolyCommonFunctions.s
	@echo ... circuit/polynomial/PolynomialCircuit.obj
	@echo ... circuit/polynomial/PolynomialCircuit.i
	@echo ... circuit/polynomial/PolynomialCircuit.s
	@echo ... circuit/polynomial/PolynomialCircuitIO.obj
	@echo ... circuit/polynomial/PolynomialCircuitIO.i
	@echo ... circuit/polynomial/PolynomialCircuitIO.s
	@echo ... circuit/polynomial/PolynomialInterpreter.obj
	@echo ... circuit/polynomial/PolynomialInterpreter.i
	@echo ... circuit/polynomial/PolynomialInterpreter.s
	@echo ... circuit/polynomial/Term.obj
	@echo ... circuit/polynomial/Term.i
	@echo ... circuit/polynomial/Term.s
	@echo ... evaluators/CategoriesEvaluator.obj
	@echo ... evaluators/CategoriesEvaluator.i
	@echo ... evaluators/CategoriesEvaluator.s
	@echo ... evaluators/FeatureEvaluator.obj
	@echo ... evaluators/FeatureEvaluator.i
	@echo ... evaluators/FeatureEvaluator.s
	@echo ... evaluators/HammingWeightEvaluator.obj
	@echo ... evaluators/HammingWeightEvaluator.i
	@echo ... evaluators/HammingWeightEvaluator.s
	@echo ... evaluators/IEvaluator.obj
	@echo ... evaluators/IEvaluator.i
	@echo ... evaluators/IEvaluator.s
	@echo ... evaluators/TopBitEvaluator.obj
	@echo ... evaluators/TopBitEvaluator.i
	@echo ... evaluators/TopBitEvaluator.s
	@echo ... generators/BiasRndGen.obj
	@echo ... generators/BiasRndGen.i
	@echo ... generators/BiasRndGen.s
	@echo ... generators/IRndGen.obj
	@echo ... generators/IRndGen.i
	@echo ... generators/IRndGen.s
	@echo ... generators/MD5RndGen.obj
	@echo ... generators/MD5RndGen.i
	@echo ... generators/MD5RndGen.s
	@echo ... generators/QuantumRndGen.obj
	@echo ... generators/QuantumRndGen.i
	@echo ... generators/QuantumRndGen.s
	@echo ... generators/md5.obj
	@echo ... generators/md5.i
	@echo ... generators/md5.s
	@echo ... projects/IProject.obj
	@echo ... projects/IProject.i
	@echo ... projects/IProject.s
	@echo ... projects/files/filesProject.obj
	@echo ... projects/files/filesProject.i
	@echo ... projects/files/filesProject.s
	@echo ... projects/pregenerated_tv/PregeneratedTvProject.obj
	@echo ... projects/pregenerated_tv/PregeneratedTvProject.i
	@echo ... projects/pregenerated_tv/PregeneratedTvProject.s
	@echo ... self_tests/TestConfigurator.obj
	@echo ... self_tests/TestConfigurator.i
	@echo ... self_tests/TestConfigurator.s
	@echo ... self_tests/Tests.obj
	@echo ... self_tests/Tests.i
	@echo ... self_tests/Tests.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /d C:\Users\Radka\Desktop\BP && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

