#ifndef HASHFUNCTIONS_H
#define HASHFUNCTIONS_H

#define SHA3_HASH_SUCCESS 0

#include "projects/sha3/hash_functions/Abacus/Abacus_sha3.h"
#include "projects/sha3/hash_functions/ARIRANG/Arirang_sha3.h"
#include "projects/sha3/hash_functions/Aurora/Aurora_sha3.h"
#include "projects/sha3/hash_functions/Blake/Blake_sha3.h"
#include "projects/sha3/hash_functions/Blender/Blender_sha3.h"
#include "projects/sha3/hash_functions/BMW/BMW_sha3.h"
#include "projects/sha3/hash_functions/Boole/Boole_sha3.h"
#include "projects/sha3/hash_functions/Cheetah/Cheetah_sha3.h"
#include "projects/sha3/hash_functions/CHI/Chi_sha3.h"
#include "projects/sha3/hash_functions/CRUNCH/Crunch_sha3.h"
#include "projects/sha3/hash_functions/CubeHash/CubeHash_sha3.h"
#include "projects/sha3/hash_functions/DCH/DCH_sha3.h"
#include "projects/sha3/hash_functions/DynamicSHA/DSHA_sha3.h"
#include "projects/sha3/hash_functions/DynamicSHA2/DSHA2_sha3.h"
#include "projects/sha3/hash_functions/ECHO/Echo_sha3.h"
// #include "projects/sha3/hash_functions/ECOH/Ecoh_sha3.h"
#include "projects/sha3/hash_functions/EDON/Edon_sha3.h"
// #include "projects/sha3/hash_functions/EnRUPT/Enrupt_sha3.h"
#include "projects/sha3/hash_functions/ESSENCE/Essence_sha3.h"
#include "projects/sha3/hash_functions/Fugue/Fugue_sha3.h"
#include "projects/sha3/hash_functions/Grostl/Grostl_sha3.h"
#include "projects/sha3/hash_functions/Hamsi/Hamsi_sha3.h"
#include "projects/sha3/hash_functions/JH/JH_sha3.h"
#include "projects/sha3/hash_functions/Keccak/Keccak_sha3.h"
#include "projects/sha3/hash_functions/Khichidi/Khichidi_sha3.h"
#include "projects/sha3/hash_functions/Lane/Lane_sha3.h"
#include "projects/sha3/hash_functions/Lesamnta/Lesamnta_sha3.h"
#include "projects/sha3/hash_functions/Luffa/Luffa_sha3.h"
// #include "projects/sha3/hash_functions/LUX/Lux_sha3.h"
#include "projects/sha3/hash_functions/MCSSHA3/Mcssha_sha3.h"
#include "projects/sha3/hash_functions/MD6/MD6_sha3.h"
#include "projects/sha3/hash_functions/MeshHash/MeshHash_sha3.h"
#include "projects/sha3/hash_functions/NaSHA/Nasha_sha3.h"
// #include "projects/sha3/hash_functions/SANDstorm/Sandstorm_sha3.h"
#include "projects/sha3/hash_functions/Sarmal/Sarmal_sha3.h"
#include "projects/sha3/hash_functions/Shabal/Shabal_sha3.h"
#include "projects/sha3/hash_functions/Shamata/Shamata_sha3.h"
#include "projects/sha3/hash_functions/SHAvite3/SHAvite_sha3.h"
#include "projects/sha3/hash_functions/SIMD/Simd_sha3.h"
#include "projects/sha3/hash_functions/Skein/Skein_sha3.h"
#include "projects/sha3/hash_functions/SpectralHash/SpectralHash_sha3.h"
#include "projects/sha3/hash_functions/StreamHash/StreamHash_sha3.h"
// #include "projects/sha3/hash_functions/SWIFFTX/Swifftx_sha3.h"
#include "projects/sha3/hash_functions/Tangle/Tangle_sha3.h"
// #include "projects/sha3/hash_functions/TIB3/Tib_sha3.h"
#include "projects/sha3/hash_functions/Twister/Twister_sha3.h"
#include "projects/sha3/hash_functions/Vortex/Vortex_sha3.h"
#include "projects/sha3/hash_functions/WaMM/Wamm_sha3.h"
#include "projects/sha3/hash_functions/Waterfall/Waterfall_sha3.h"

#endif // HASHFUNCTIONS_H
